# Generated by Django 4.1.2 on 2022-11-23 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
