# Generated by Django 4.1.2 on 2022-10-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
    ]
