# Generated by Django 4.1.2 on 2022-11-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0003_configuracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=500)),
                ('hobbie', models.CharField(max_length=100)),
                ('deporte', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_casa', models.CharField(max_length=100)),
                ('habitaciones', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
    ]
