# Generated by Django 4.1.2 on 2022-11-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0004_datos_vivienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='tipo_casa',
            field=models.CharField(default='', max_length=100),
        ),
    ]
